# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: Dayo's Website
description: >- # this means to ignore newlines until "baseurl:"
  Enterprise Network Engineer with a passion for technology and DIY projects.

# Select a theme for your site (optional, but recommended)
theme: jekyll-theme-minimal
